image: python:3.10-bullseye

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    when: always
  - when: never

before_script:
  - apt-get update
  - export PYTHONPATH="$PYTHONPATH:`pwd`"
  - cat requirements.txt | sed "s/torch==2.5.1/torch @ https:\/\/download.pytorch.org\/whl\/cpu\/torch-2.5.1%2Bcpu-cp310-cp310-linux_x86_64.whl/g" > /tmp/requirements_ci.txt
  - pip install -r /tmp/requirements_ci.txt
  - pip install pylint pytest

test:
  script:
  - cd test/
  - python -m pytest .

pylint:
  script:
  - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test/\|examples/\|\bsetup.py\b")
